
float32 roll	    # body angular rates in NED frame
float32 pitch	    # body angular rates in NED frame
float32 yaw			# body angular rates in NED frame
float32 thrust	    # thrust normalized to 0..1

#add for wangxy668 2018-4-25
float32 DT
float32 AT
float32 Beta
float32 BetaT
float32 U
float32 Rt0
float32 Rt1
float32 Tp0


# TOPICS vehicle_rates_setpoint mc_virtual_rates_setpoint fw_virtual_rates_setpoint
